---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: anm-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8090
    requestPath: /login/
    type: HTTPS
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: apimgr-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8075
    requestPath: /
    type: HTTPS
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: apitraffic-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    requestPath: /healthcheck
    type: HTTP