# A sample myvalues.yaml file
apibuilder4elastic: 
  imageTag: "latest"
  imagePullPolicy: Always
  replicas: 1
  anmUrl: "https://axway-apim-anm:8090"
  apimgrUrl: "https://apimgr:8075"
  secrets: 
    apimgrUsername: "apiadmin"
    apimgrPassword: "axway123"

  validateElasticsearchCertificate: "false"

  apmserver:
    verifyServerCert: "false"
  logLevel: debug
  eventlogCustomAttributes: "user-agent"
  retentionPeriodConfig: "./config/my-retention-period.json"

  extraVolumes:
    - name: retentionperiod
      configMap:
        name: retentionperiod

  extraVolumeMounts: 
    - name: retentionperiod
      mountPath: /app/config/

# Enable, if you would like to deploy a new Elasticsearch cluster for the solution
elasticsearch:
  enabled: true
  # imageTag: "7.16.2"
  replicas: 3
  extraInitContainers: [] # To be removed on release after 3.2.0
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: gp2
    resources:
      requests:
        storage: 120Gi
  esJavaOpts: "-Xms4g -Xmx4g"
  resources:
    requests:
      cpu: "2000m"
      memory: "8Gi"
    limits:
      cpu: "4000m"
      memory: "8Gi"

  # For this demo environment it's okay to have two ES-Nodes on the same worker node
  antiAffinity: "ignore"

  # Enabling this will publicly expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  ingress: 
    enabled: false

# Enable, if you would like to deploy Kibana for the solution
kibana:
  enabled: true
  # imageTag: "7.16.2"
  validateElasticsearchCertificate: "none"
  ingress:
    className: ""
    # Annotations used to expose Kibana on an AWS-ALB
    # See here for more information
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: axway-apim
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # 302 is also accepted, as Kibana is performing a redirect
      alb.ingress.kubernetes.io/success-codes: 200,302
    hosts:
      - host: kibana.axway-apim-on-eks.de
        paths:
          - path: /*

  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "700Mi"

logstash:
  replicas: 2
  # imageTag: "7.16.2"
  logstashJavaOpts: "-Xmx6g -Xms6g"
  validateElasticsearchCertificate: "none"
  resources:
    requests:
      cpu: "2000m"
      memory: "6Gi"
    limits:
      cpu: "3000m"
      memory: "6Gi"

  cacheAPIPaths: "/petstore/v2/pet, /careplan/"

filebeat: 
  # Only create the ConfigMaps which are used by Filebeat running along the API-Gateways as a side-car
  createFilebeatConfig: true
  # imageTag: "7.16.2"

  elasticsearchClusterUUID: Vg0PRj28SY2mLuOEkzMMng

  validateElasticsearchCertificate: "none"

  filebeatSecrets: 
    beatsSystemUsername: ""

  compressionLevel: 9

apm-server:
  enabled: true

  elasticsearchClusterUUID: i1djDUVbTcKj2ySgf1PCmg

  validateElasticsearchCertificate: "none"

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "250Mi"