name: Deploy EMR-Catalog API

on:
  push:
    branches:
      - main
    paths:
      - api-emr-catalog/**

jobs:
  API-Deployment:
    env:
      workingDirectory: 'api-emr-catalog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: List current directory
        run: |
          ls -la
      - name: Deploy API
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        run: |
          printenv
          cd ${{env.working-directory}}
          mvn clean exec:java