name: Deploy ATM-Locator API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - atm-locator-app/**

defaults:
  run:
    working-directory: atm-locator-app

jobs:
  API-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: hmarr/debug-action@v1.0.0
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #- name: Debug some stuff
      #  run: |
      #    echo ${{ github.event_name }}
      - name: Deploy API to Integration
        if: ${{ github.event_name == 'pull_request' }}
        env:
          APIM_USER: ${{ secrets.APIM_USER_INT }}
          APIM_PASS: ${{ secrets.APIM_PASS_INT }}
          APIM_HOST: ${{ secrets.APIM_HOST_INT }}
          APIM_PORT: ${{ secrets.APIM_PORT_INT }}
        run: |
          mvn clean exec:java
      - name: Deploy API to QA
        if: ${{ github.event_name != 'pull_request' }}
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        run: |
          mvn clean exec:java

  test-api:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Test API
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install newman
        run: sudo npm -g install newman
      - name: Run Integration-API tests
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sleep 1
          newman run ./tests/ATM-Locator-API.postman_collection.json -e ../lib/Integration-Environment.postman_environment.json --reporter-json-export output.json --insecure
      - name: Run QA-API tests
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          sleep 1
          newman run ./tests/ATM-Locator-API.postman_collection.json -e ../lib/Demo-Environment.postman_environment.json --reporter-json-export output.json --insecure