name: Deploy Client Applications

on:
  push:
    branches:
      - main
    paths:
      - setup/ClientApps/**

defaults:
  run:
    working-directory: setup

jobs:
  deploy-client-apps:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Deploy Client Applications
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy Client apps
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        run: |
          ./setupOrgsAndApps.sh apps
        